Repository runme-io/website, pull requests merged in 2020-06, with the labels that each got.

#156 fix(spec-generator): remove command in yaml result
  src/Helpers/SpecGenerator.js
Labels: Bug

#157 Release 05.06.2020
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  commitlint.config.js
  package-lock.json
  package.json
  src/Consts/Environment.js
  src/Consts/index.js
  src/Helpers/Modal.js
  src/Helpers/SpecGenerator.js
  src/Helpers/copyToClipboard.js
  src/Helpers/index.js
  src/assets/style/_tippy.sass
  src/assets/style/mixins.sass
  src/assets/style/theme.sass
  src/components/Actions/index.js
  src/components/Actions/tooltip.js
  src/components/Runme/GenerateResult.svelte
  src/components/Runme/GenerateSpecResult.svelte
  src/components/Runme/GenerateSpecTabGroup.svelte
  src/components/Runme/Generator/GenerateButton.svelte
  src/components/Runme/Generator/OptionEnvVars.svelte
  src/components/Runme/SpecGenerator/SpecResultHeader.svelte
  src/components/Stores/Header.js
  src/components/UI/Button/Button.svelte
  src/components/UI/Button/ButtonDropdown.svelte
  src/components/UI/Button/ButtonDropdownOption.svelte
  src/components/UI/Button/ButtonIcon.svelte
  src/components/UI/Button/index.js
  src/components/UI/Code.svelte
  src/components/UI/Copy.svelte
  src/components/UI/Donation.svelte
  src/components/UI/Footer/Donation.svelte
  src/components/UI/Footer/MainFooter.svelte
  src/components/UI/Footer/SocialIcons.svelte
  src/components/UI/Footer/SubFooter.svelte
  src/components/UI/Footer/TechnologyLogos.svelte
  src/components/UI/GitHub/GithubMarkdown.svelte
  src/components/UI/GitHub/GithubPanel.svelte
  src/components/UI/Header/ActionDropdown.svelte
  src/components/UI/Layout/FixedHeader.svelte
  src/components/UI/Layout/JexiaFooter.svelte
  src/components/UI/Layout/MainLayout.svelte
  src/components/UI/Layout/RunmeFooter.svelte
  src/components/UI/Layout/TechnologyLogos.svelte
  src/components/UI/Link.svelte
  src/components/UI/MetaData.svelte
  src/components/UI/Modals/DockerCommandsModal.svelte
  src/components/UI/Modals/ModalLayout.svelte
  src/components/UI/MultipleTextInput.svelte
  src/components/UI/Popover/PopoverCopy.svelte
  src/components/UI/SocialIcons.svelte
  src/routes/_error.svelte
  src/routes/build.svelte
  src/routes/index.svelte
  src/routes/robots.txt.js
  src/routes/run.svelte
  src/routes/show.svelte
Labels: Release

#160 fix(show): check apps for status higher than 500 for success
  src/routes/show.svelte
Labels: Bug

#161 Release 09.06.2020
  src/routes/show.svelte
  static/data/docker-images.json
Labels: Release

#162 fix(docker-images): deno versions
  static/data/docker-images.json
Labels: Bug

#163 Release 09.06.2020
  static/data/docker-images.json
Labels: Release

#166 feat(error-page): better styling
  src/assets/style/theme.sass
  src/components/UI/Layout/FixedHeader.svelte
  src/routes/_error.svelte
Labels: Enhancement

#167 fix(fixed-header): animated logo on demand
  src/components/UI/Header/FixedHeaderLogo.svelte
  src/components/UI/Layout/FixedHeader.svelte
  src/routes/_error.svelte
Labels: Bug

#168 refactor(api-request): better throw handling
  src/Helpers/Const.js
  src/Helpers/RunmeApi.js
  src/Helpers/WebSocket.js
  src/Helpers/index.js
Labels: Tech Debt

#169 refactor(header): move header files to specific folder
  src/components/UI/Header/FixedHeader.svelte
  src/components/UI/Header/Header.svelte
  src/components/UI/Layout/MainLayout.svelte
  src/routes/_error.svelte
  src/routes/build.svelte
  src/routes/run.svelte
  src/routes/show.svelte
Labels: Tech Debt

#170 feat: setup release bot
  .github/workflows/release.yaml
  package-lock.json
  package.json
Labels: Enhancement

#171 Release 23.06.2020
  .github/workflows/release.yaml
  package-lock.json
  package.json
  src/Helpers/Const.js
  src/Helpers/QueryParam.js
  src/Helpers/RunmeApi.js
  src/Helpers/WebSocket.js
  src/Helpers/index.js
  src/assets/style/theme.sass
  src/components/Stores/Application.js
  src/components/UI/Cli/CliWindow.svelte
  src/components/UI/Header/FixedHeader.svelte
  src/components/UI/Header/FixedHeaderLogo.svelte
  src/components/UI/Header/Header.svelte
  src/components/UI/Layout/MainLayout.svelte
  src/routes/_error.svelte
  src/routes/build.svelte
  src/routes/run.svelte
  src/routes/show.svelte
Labels: Release

#172 feat(readme): add release badge
  README.md
  package-lock.json
Labels: Documentation, Task

#173 Release 23.06.2020-2
  README.md
  package-lock.json
Labels: Release

#174 fix(build): close websocket when needed
  src/Helpers/RunmeApi.js
  src/components/Stores/Build.js
Labels: Bug

#176 fix(docker-commands): invalid run command
  src/components/UI/Modals/DockerCommandsModal.svelte
Labels: Bug

#177 Release 26.06.2020
  src/Helpers/RunmeApi.js
  src/components/Stores/Build.js
  src/components/UI/Modals/DockerCommandsModal.svelte
Labels: Release

#175 feat(deploy-to-jexia): enable deploy of applications
  src/components/Stores/Header.js
  src/routes/show.svelte
Labels: Feature
